---
apiVersion: v1
kind: Service
metadata:
  name: zk-hs
  labels:
    app: zk
spec:
  ports:
  - port: 2888
    name: server
  - port: 3888
    name: leader-election
  clusterIP: None
  selector:
    app: zk
---
apiVersion: v1
kind: Service
metadata:
  name: zk-cs
  labels:
    app: zk
spec:
  ports:
  - port: 2181
    name: client
  selector:
    app: zk
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: zk
spec:
  serviceName: zk-hs
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: zk
    spec:
      containers:
      - name: kubernetes-zookeeper
        imagePullPolicy: Always
        image: "docker-registry.default.svc:5000/dzookeeper/zookeeperprod:latest"
        resources:
          requests:
            memory: "1Gi"
            cpu: "0.5"
        ports:
        - containerPort: 2181
          name: client
        - containerPort: 2888
          name: server
        - containerPort: 3888
          name: leader-election
        env:
          - name: ZOO_SERVERS
            value: server.1=zk-0.zk-hs.dzookeeper.svc.cluster.local:2888:3888 server.2=zk-1.zk-hs.dzookeeper.svc.cluster.local:2888:3888 server.3=zk-2.zk-hs.dzookeeper.svc.cluster.local:2888:3888
        readinessProbe:
          exec:
            command:
            - sh
            - -c
            - "/zookeeper-ready.sh 2181"
          initialDelaySeconds: 40
          timeoutSeconds: 15
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - "/zookeeper-ready.sh 2181"
          initialDelaySeconds: 40
          timeoutSeconds: 15
        volumeMounts:
        - name: datadir
          mountPath: /data
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
